[versions]
activityComposeVersion = "1.12.2"
agp = "8.13.2"
appcompatVersion = "1.7.1"
browserVersion = "1.9.0"
coilComposeVersion = "2.7.0"
coilVideoVersion = "2.7.0"
composeBomVersion = "2025.12.01"
constraintlayoutVersion = "2.2.1"
coreKtxVersion = "1.17.0"
chaquo = "17.0.0"
firebaseAuthKtxVersion = "23.2.1"
firebaseBomVersion = "34.7.0"
glideVersion = "5.0.5"
gms = "4.4.4"
junitJunit = "4.13.2"
kotlin = "2.3.0"
kotlinStdlibVersion = "2.3.0"
kotlinxSerializationJsonVersion = "1.9.0"
lifecycleLivedataKtxVersion = "2.10.0"
lifecycleViewmodelComposeVersion = "2.10.0"
lifecycleViewmodelKtxVersion = "2.10.0"
media3Version = "1.9.0"
mediaVersion = "1.7.1"
nav3Core = "1.0.0"
playServicesAuthVersion = "21.5.0"
runtimeAndroidVersion = "1.10.0"
runtimeLivedataVersion = "1.10.0"
uiViewbindingVersion = "1.10.0"
firebaseFirestoreKtxVersion = "25.1.4"
googleidVersion = "1.1.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coilVideoVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtxVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlibVersion" }
junit = { module = "junit:junit", version.ref = "junitJunit" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material3 = { module = "androidx.compose.material3:material3" }
media = { module = "androidx.media:media", version.ref = "mediaVersion" }
media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "media3Version" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Version" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Version" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Version" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3Version" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Version" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Version" }
media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3Version" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
runtime-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "runtimeAndroidVersion" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedataVersion" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "uiViewbindingVersion" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtxVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleidVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
chaquo-python = { id = "com.chaquo.python", version.ref = "chaquo" }
google-gms = { id = "com.google.gms.google-services", version.ref = "gms" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
