[versions]
activityComposeVersion = "1.13.0"
agp = "9.2.1"
appcompatVersion = "1.7.1"
browserVersion = "1.10.0"
coilComposeVersion = "2.7.0"
coilVideoVersion = "2.7.0"
composeBomVersion = "2026.05.01"
coreKtxVersion = "1.18.0"
chaquo = "17.0.0"
datastorePreferencesVersion = "1.2.1"
firebaseBomVersion = "34.13.0"
glideVersion = "5.0.7"
gms = "4.4.4"
hiltVersion = "2.59.2"
hiltNavigationComposeVersion = "1.3.0"
kotlinxCoroutinesAndroidVersion = "1.11.0"
kspVersion = "2.3.6"
kotlin = "2.3.21"
kotlinxSerializationJsonVersion = "1.11.0"
lifecycleViewmodelComposeVersion = "2.10.0"
lifecycleViewmodelKtxVersion = "2.10.0"
media3Version = "1.10.1"
mediaVersion = "1.8.0"
nav3Core = "1.1.2"
ktor = "3.5.0"
room3Version = "3.0.0-alpha05"
runtimeAndroidVersion = "1.11.2"
firestoreVersion = "26.3.0"
lifecycleRuntimeKtxVersion = "2.10.0"
dasPython = "1.0.0"
dasDownloader = "1.0.5"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesVersion" }
androidx-room3-runtime = { group = "androidx.room3", name = "room3-runtime", version.ref = "room3Version" }
androidx-room3-compiler = { group = "androidx.room3", name = "room3-compiler", version.ref = "room3Version" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coilVideoVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroidVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material3 = { module = "androidx.compose.material3:material3" }
media = { module = "androidx.media:media", version.ref = "mediaVersion" }
media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "media3Version" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Version" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Version" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Version" }
media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3Version" }
media3-ui-material3 = { module = "androidx.media3:media3-ui-compose-material3", version.ref = "media3Version" }

#Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

runtime-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "runtimeAndroidVersion" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firestoreVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

#MYProject
com-das-python = { group = "com.das", name = "python", version.ref = "dasPython"}
com-das-downloader = { group = "com.das", name = "downloader", version.ref = "dasDownloader" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
chaquo-python = { id = "com.chaquo.python", version.ref = "chaquo" }
google-gms = { id = "com.google.gms.google-services", version.ref = "gms" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion"}
room3 = { id = "androidx.room3", version.ref = "room3Version" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion"}